# Generated by Django 5.2.7 on 2025-11-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='account',
        ),
        migrations.RemoveField(
            model_name='card',
            name='issuer',
        ),
    ]
